language: minimal

services:
  - docker

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

before_install:
install:

script:
#- security/dump_sec_updates.sh
#- git add . && git commit -m "autocommit sec updates" && git push
- cd test/01-devmode && ./kickstart.sh :test
- curl -X POST --data "" $DAILY_DOCKERHUB_PULL_URL

