name: build-testing-daily

# Build daily 03:00
on:
  schedule:
      # * is a special character in YAML so you have to quote this string
      # Run only Wednesdays at 3:00
      - cron:  '0 3 * * 3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Run a one-line script
      run: cd test/01-devmode && ./kickstart.sh :test

    - name: Trigger testing run
      run: "curl -X POST --data '{\"docker_tag\": \"testing\"}' ${{ secrets.DAILY_DOCKERHUB_PULL_URL }}"
